TumblrTools.Viewer/Controllers/DownloadController.cs
namespace TumblrTools.Viewer.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using TumblrTools.Application;
    using TumblrTools.Domain;
    using TumblrTools.Generic;

    public class DownloadController : BaseController
    {
        private readonly IDownloadRepository downloadRepository;

        public DownloadController(IConfiguration configuration, ILogger logger)
            : base(configuration, logger)
        {
            IRepositoryBuilder repositoryBuilder = this.GetRepositoryBuilder();
            this.downloadRepository = repositoryBuilder.DownloadRepository;
        }

        [Route("blogs")]
        [HttpGet]
        public ActionResult Index()
        {
            return this.View(this.downloadRepository.GetAllSortedByBlogId());
        }

        [Route("blogs/create")]
        [HttpPost]
        public ActionResult Create(string blogId, string tags)
        {
            EntriesService entryService = new EntriesService(this.Logger, this.downloadRepository);
            entryService.AddOrUpdateEntry(blogId, DownloadEntry.SplitTags(tags).ToArray());
            return this.View("Index", this.downloadRepository.GetAllSortedByBlogId());
        }

        [Route("blogs/delete")]
        [HttpPost]
        public ActionResult Delete(string blogId)
        {
            EntriesService entryService = new EntriesService(this.Logger, this.downloadRepository);
            entryService.RemoveEntry(blogId);
            return this.View("Index", this.downloadRepository.GetAllSortedByBlogId());
        }

    }
}

TumblrTools.Viewer/Views/Download/Index.cshtml
@model IEnumerable<TumblrTools.Domain.DownloadEntry>

<h2>Blogs</h2>

@using (Html.BeginForm("Create", "Download", FormMethod.Post)) {
    <input name="blogId" />
    <input name="tags" />
    <button type="submit">Create</button>
}

<table class="table">
    <tr>
        <th>
            BlogId
        </th>
        <th>
            Tags
        </th>
        <th>
            Last update
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="http://@(item.BlogId).tumblr.com">@item.BlogId</a>
        </td>
        <td>
            @item.TagList()
        </td>
        <td>
            @item.LastUpdate
        </td>
        <td>
            @using (Html.BeginForm("Delete", "Download", FormMethod.Post))
            {
                @Html.Hidden("blogId", item.BlogId)
                <button type="submit">Delete</button>
            }
        </td>
    </tr>
}

</table>